spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/microservices-java?createDatabaseIfNotExist=true
        username: root
        password: 1234

    jpa:
        show-sql: true